# adds additional scrape configs to prometheus.yml
# must be a string so you have to add a | after extraScrapeConfigs:
# example adds prometheus-blackbox-exporter scrape config

extraScrapeConfigs: |
  - job_name: 'kvstore'
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
    - targets: ['kvstore-service:8080']
